title: "Sample-efficient Cross-Entropy Method for Real-time Planning"
description: Supplementary Website

username: sample-efficient-cross-entropy
email: sample.efficient.cross.entropy@gmail.com

authors: "Cristina Pinneri, Shambhuraj Sawant, Sebastian Blaes, Jan Achterhold, J&ouml;rg St&uuml;ckler, Michal Rol&iacute;nek, Georg Martius"
