title: "Self-supervised Visual Reinforcement Learning with Object-centric Representations"
description: Supplementary Website

username: zadaianchuk
email: andrii.zadaianchuk@tuebingen.mpg.de

authors: "Andrii Zadaianchuk, Maximilian Seitzer, Georg Martius"
